src/Entity/Restaurant.php
<?php

namespace App\Entity;

use App\Repository\RestaurantRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;

#[ORM\Entity(repositoryClass: RestaurantRepository::class)]
class Restaurant
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    private ?int $id = null;

    #[ORM\Column(length: 150)]
    private ?string $name = null;

    #[ORM\Column(type: Types::TEXT)]
    private ?string $description = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    private ?\DateTimeInterface $createdAt = null;

    #[ORM\ManyToOne(inversedBy: 'restaurants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Ville $ville = null;

    #[ORM\ManyToOne(inversedBy: 'restaurants')]
    #[ORM\JoinColumn(nullable: false)]
    private ?User $user = null;

    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: RestaurantPicture::class)]
    private Collection $restaurantPictures;

    #[ORM\OneToMany(mappedBy: 'restaurant', targetEntity: Avis::class, orphanRemoval: true)]
    private Collection $avis;

    public function __construct()
    {
        $this->restaurantPictures = new ArrayCollection();
        $this->avis = new ArrayCollection();
        $this->createdAt = new \DateTime();
    }

    public function getRating(): ?float
    {
        $total = 0;
        foreach ($this->avis as $avi) {
            $total += $avi->getRating();
        }
        return $total / count($this->avis);
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getName(): ?string
    {
        return $this->name;
    }

    public function setName(string $name): static
    {
        $this->name = $name;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): static
    {
        $this->description = $description;

        return $this;
    }

    public function getCreatedAt(): ?\DateTimeInterface
    {
        return $this->createdAt;
    }

    public function setCreatedAt(\DateTimeInterface $createdAt): static
    {
        $this->createdAt = $createdAt;

        return $this;
    }

    public function getVille(): ?Ville
    {
        return $this->ville;
    }

    public function setVille(?Ville $ville): static
    {
        $this->ville = $ville;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): static
    {
        $this->user = $user;

        return $this;
    }

    /**
     * @return Collection<int, RestaurantPicture>
     */
    public function getRestaurantPictures(): Collection
    {
        return $this->restaurantPictures;
    }

    public function addRestaurantPicture(RestaurantPicture $restaurantPicture): static
    {
        if (!$this->restaurantPictures->contains($restaurantPicture)) {
            $this->restaurantPictures->add($restaurantPicture);
            $restaurantPicture->setRestaurant($this);
        }

        return $this;
    }

    public function removeRestaurantPicture(RestaurantPicture $restaurantPicture): static
    {
        if ($this->restaurantPictures->removeElement($restaurantPicture)) {
            // set the owning side to null (unless already changed)
            if ($restaurantPicture->getRestaurant() === $this) {
                $restaurantPicture->setRestaurant(null);
            }
        }

        return $this;
    }

    /**
     * @return Collection<int, Avis>
     */
    public function getAvis(): Collection
    {
        return $this->avis;
    }

    public function addAvi(Avis $avi): static
    {
        if (!$this->avis->contains($avi)) {
            $this->avis->add($avi);
            $avi->setRestaurant($this);
        }

        return $this;
    }

    public function removeAvi(Avis $avi): static
    {
        if ($this->avis->removeElement($avi)) {
            // set the owning side to null (unless already changed)
            if ($avi->getRestaurant() === $this) {
                $avi->setRestaurant(null);
            }
        }

        return $this;
    }
}

templates/components/restaurantCard.html.twig
<div style="width: 300px">
  <div class="card">
    <div class="card-body">
      <h4 class="card-title">{{ restaurant.name }}</h4>
      <h6 class="card-subtitle mb-2 text-muted">
        {{ restaurant.user.firstname }}
      </h6>
      <p class="card-text">{{ restaurant.description }}</p>
      <p class="card-text">
        {{ restaurant.ville.name }} - {{ restaurant.ville.codePostal }}
      </p>
      <p class="card-text">
        {{ restaurant.rating | number_format(2)}}
      </p>
      <div class="card-footer text-muted d-flex justify-content-between">
        <span> {{ restaurant.createdAt | ago }}</span>
        <div class="d-flex justify-content-end">
          <a href="{{ path('app_restaurant_show', { id: restaurant.id }) }}"
            >Voir</a
          >
          {% if is_granted('ROLE_MODERATEUR') or
          (is_granted('ROLE_RESTAURATEUR') and restaurant.user == app.user) %}
          <a href="{{ path('app_restaurant_edit', { id: restaurant.id }) }}"
            >Modifier</a
          >
          {% endif %}
        </div>
      </div>
    </div>
  </div>
</div>